"""Generate the committed lint-diagnostics ledger for the failure-taxonomy appendix.

Verilator's per-sample lint log (``sample_N.log``) is not part of the signed manifest
contract and, like ``results/refs/`` (see ``scripts/generate_reference_metrics.py``), is
local scratch: gitignored, regenerated by re-running the campaign, and never committed.
This script is the one-time bridge from that local scratch to a small, committed,
deterministic ledger (``paper/data/lint_diagnostics_ledger.json``) recording, for every
(model, task) pair whose first failing stage is lint, which Verilator diagnostic codes
fired. ``paper/data/generate_failure_taxonomy.py`` consumes only the committed ledger
(never the raw logs) and cross-validates its key set against the signed manifests before
trusting it, so a reader who has the repository but not this machine's local results
directory can still verify the ledger is internally consistent with the evidence it cites.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from harness.schemas.manifest import load_manifest  # noqa: E402

DIAG_CODE_RE = re.compile(r"%(?:Warning|Error)-([A-Z0-9]+)")


def _lint_failing_pairs(results_root: Path) -> dict[str, Path]:
    """Return {"model/task_id": manifest_path} for every pair whose first failing
    stage is lint on a real, scored submission.

    A manifest's ``generation_error`` field -- not local ``.sv`` file presence -- is
    the authoritative signal for whether a submission was ever scored: a stale
    ``sample_1.sv`` can survive on disk from an earlier attempt in the same task
    directory even when the run that produced the *committed* manifest failed before
    generation (e.g. a provider transport error), so checking file presence instead of
    ``generation_error`` silently misclassifies those pairs. Must stay in lockstep with
    the classification in ``paper/data/generate_failure_taxonomy.py``'s ``_classify``.
    """

    pairs: dict[str, Path] = {}
    for manifest_path in sorted(results_root.glob("*/*/sample_1.json")):
        manifest = load_manifest(manifest_path)
        if manifest.task_score != 0 or manifest.generation_error is not None:
            continue
        stages = {stage.name: stage.status for stage in manifest.stages}
        if stages.get("lint") != "fail":
            continue
        model = manifest_path.parent.parent.name
        task_id = manifest_path.parent.name
        pairs[f"{model}/{task_id}"] = manifest_path
    return pairs


def generate_ledger(results_root: str | Path) -> dict[str, object]:
    root = Path(results_root)
    pairs = _lint_failing_pairs(root)
    entries: dict[str, list[str]] = {}
    for key, manifest_path in pairs.items():
        log_path = manifest_path.with_suffix(".log")
        if not log_path.is_file():
            raise ValueError(f"missing lint log for lint-failing pair {key}: {log_path}")
        text = log_path.read_text(encoding="utf-8", errors="strict")
        codes = sorted(set(DIAG_CODE_RE.findall(text)))
        entries[key] = codes
    return {
        "schema_version": 1,
        "generated_from": "local sample_1.log files under results/eval-16384 (gitignored, not committed)",
        "diagnostic_code_pattern": DIAG_CODE_RE.pattern,
        "pairs": dict(sorted(entries.items())),
    }


def _render(raw: dict[str, object]) -> str:
    return json.dumps(raw, indent=2, sort_keys=True) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--results-root", default="results/eval-16384")
    parser.add_argument(
        "--out", default=str(REPO_ROOT / "paper" / "data" / "lint_diagnostics_ledger.json")
    )
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)

    try:
        rendered = _render(generate_ledger(args.results_root))
    except (OSError, ValueError) as exc:
        print(f"lint diagnostics ledger generation failed: {exc}", file=sys.stderr)
        return 1

    output = Path(args.out)
    if args.check:
        if not output.is_file() or output.read_text(encoding="utf-8") != rendered:
            print(f"lint diagnostics ledger is stale: {output}", file=sys.stderr)
            return 1
        print("lint diagnostics ledger check: PASS")
        return 0
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {len(json.loads(rendered)['pairs'])} lint-failure diagnostics to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
