"""Generate paper_facts.tex: numeric facts cited in main.tex prose, derived from raw evidence.

Several prose paragraphs in main.tex (the RTLLM operator-mix discussion, the mutant-count
tercile split, the at-100%/below-95% design counts) cite specific numbers that previously drifted
out of sync with the underlying data -- most of the discrepancies this generator exists to prevent
were found and fixed in this same pass. Rather than re-typing numbers by hand again, this script
computes them from the same source generate_audit_appendix.py already validates
(external-audit/results/rtllm/final-g2012/*.json) and emits \newcommand macros main.tex can cite
by name, so a future raw-data change breaks the paper compile instead of silently going stale.

Deliberately narrow: this covers only the specific derived quantities this pass needed to check
prose against. It is not a general-purpose fact database.
"""

from __future__ import annotations

import argparse
import statistics
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from paper.data.generate_audit_appendix import (  # noqa: E402
    AUDIT_DIR,
    AuditAppendixDataError as TableDataError,
    load_designs,
)

OUT_PATH = REPO_ROOT / "paper" / "data" / "build" / "paper_facts.tex"


def _tercile_medians(audited: list[dict]) -> tuple[float, float, float]:
    """Split into 15/15/16 by mutant count, ties broken by task_id. Caller guarantees len==46."""
    by_count = sorted(audited, key=lambda r: (r["mutants_total"], r["task_id"]))
    t1, t2, t3 = by_count[:15], by_count[15:30], by_count[30:]
    return (
        statistics.median(r["kill_rate"] for r in t1),
        statistics.median(r["kill_rate"] for r in t2),
        statistics.median(r["kill_rate"] for r in t3),
    )


def collect(audit_dir: Path = AUDIT_DIR) -> dict:
    audited, unsupported = load_designs(audit_dir)

    total_mutants = sum(r["mutants_total"] for r in audited)
    total_killed = sum(r["killed"] for r in audited)
    total_survived = sum(r["survived"] for r in audited)
    total_indeterminate = sum(r["indeterminate"] for r in audited)
    if total_killed + total_survived + total_indeterminate != total_mutants:
        raise TableDataError("killed + survived + indeterminate != mutants_total")

    at_100 = sum(1 for r in audited if r["kill_rate"] == 100.0)
    below_95 = sum(1 for r in audited if r["kill_rate"] < 95.0)
    if at_100 + below_95 != len(audited):
        raise TableDataError("at_100 + below_95 must cover every audited design (none in [95,100))")

    op_total: dict[str, int] = {}
    op_survived: dict[str, int] = {}
    for r in audited:
        for m in r["per_mutant"]:
            op = m["operator"]
            op_total[op] = op_total.get(op, 0) + 1
            if m["verdict"] == "survived":
                op_survived[op] = op_survived.get(op, 0) + 1
    if sum(op_total.values()) != total_mutants:
        raise TableDataError("operator_counts do not sum to total_mutants")

    if len(audited) != 46:
        raise TableDataError(f"tercile split assumes 46 audited designs, found {len(audited)}")
    t1_med, t2_med, t3_med = _tercile_medians(audited)

    return {
        "audited": len(audited),
        "unsupported": len(unsupported),
        "total_mutants": total_mutants,
        "total_killed": total_killed,
        "total_survived": total_survived,
        "total_indeterminate": total_indeterminate,
        "at_100": at_100,
        "below_95": below_95,
        "below_95_pct": 100 * below_95 / len(audited),
        "op_total": op_total,
        "op_survived": op_survived,
        "tercile_medians": (t1_med, t2_med, t3_med),
    }


def render(facts: dict) -> str:
    lines = ["% generated by paper/data/generate_paper_facts.py -- do not hand-edit"]

    def macro(name: str, value: object) -> None:
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}")

    macro("FactsAudited", facts["audited"])
    macro("FactsUnsupported", facts["unsupported"])
    macro("FactsTotalMutants", facts["total_mutants"])
    macro("FactsTotalKilled", facts["total_killed"])
    macro("FactsTotalSurvived", facts["total_survived"])
    macro("FactsTotalIndeterminate", facts["total_indeterminate"])
    macro("FactsAtHundred", facts["at_100"])
    macro("FactsBelowNinetyFive", facts["below_95"])
    macro("FactsBelowNinetyFivePct", f"{facts['below_95_pct']:.0f}")
    for op, count in sorted(facts["op_total"].items()):
        safe = "".join(w.capitalize() for w in op.split("_"))
        macro(f"FactsOp{safe}", count)
        survived = facts["op_survived"].get(op, 0)
        pct = 100 * survived / count if count else 0.0
        macro(f"FactsOp{safe}SurvivedPct", f"{pct:.0f}")
    t1, t2, t3 = facts["tercile_medians"]
    macro("FactsTercileOneMedian", f"{t1:.1f}")
    macro("FactsTercileTwoMedian", f"{t2:.1f}")
    macro("FactsTercileThreeMedian", f"{t3:.1f}")
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--audit-dir", type=Path, default=AUDIT_DIR)
    parser.add_argument("--out", type=Path, default=OUT_PATH)
    args = parser.parse_args(argv)

    try:
        facts = collect(args.audit_dir)
    except TableDataError as exc:
        parser.exit(2, f"paper_facts generation refused: {exc}\n")

    rendered = render(facts)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {args.out}")
    print(f"  audited={facts['audited']} unsupported={facts['unsupported']}")
    print(f"  at_100={facts['at_100']} below_95={facts['below_95']} ({facts['below_95_pct']:.0f}%)")
    print(f"  terciles: {facts['tercile_medians']}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
