"""Generate the Track A leaderboard for the raised-output-budget (16,384-token) campaign.

Kept separate from generate_tables.py, which owns the original 4096-token campaign tables. Reads a
results tree laid out as <root>/<model-dir>/summary.json and emits a LaTeX fragment.

Unlike the 4096 table this one reports Pass@1 and mean PPA over passed tasks as explicit columns:
the original table carried a constant "Tasks = 60" column that conveyed nothing, while Pass@1 --- the
metric that actually drives the ranking --- had to be recovered from the prose.

Discovery and validation are delegated entirely to generate_tables.load_evaluations: the same
signature verification, exact-60-task-set requirement, per-task manifest cross-check, and
ambiguous-duplicate-run rejection this script's sibling tables already enforce. This script no
longer does its own unvalidated JSON parsing.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from paper.data.generate_tables import EvalRecord, TableDataError, load_evaluations  # noqa: E402

EXPECTED_MODEL_COUNT = 7

PROVIDER_OF = {
    "claude-opus-4-8": "anthropic",
    "claude-sonnet-4-6": "anthropic",
    "claude-haiku-4-5-20251001": "anthropic",
    "gpt-5": "openai",
    "gpt-5-mini": "openai",
    "google/gemini-2.5-pro": "openrouter",
    "meta-llama/llama-4-maverick": "openrouter",
}


def _tex(value: str) -> str:
    return value.replace("_", r"\_").replace("&", r"\&")


def _provider(row: EvalRecord) -> str:
    known = PROVIDER_OF.get(row.model)
    if known is not None and known != row.provider:
        raise TableDataError(
            f"provider mismatch for {row.model}: summary says {row.provider!r}, "
            f"expected {known!r}"
        )
    return row.provider


def collect(
    root: Path,
    expected_task_ids: frozenset[str] | None = None,
) -> list[EvalRecord]:
    rows = load_evaluations(root, expected_task_ids)
    if len(rows) != EXPECTED_MODEL_COUNT:
        raise TableDataError(
            f"expected {EXPECTED_MODEL_COUNT} models under {root}, found {len(rows)}: "
            f"{[row.model for row in rows]}"
        )
    return rows


def render(rows: list[EvalRecord]) -> str:
    lines = [
        "% generated by paper/data/generate_tracka_16384.py -- do not hand-edit",
        r"\begin{tabular}{llrrrrr}",
        r"\toprule",
        r"Provider & Model & Pass@1 & Score & Mean PPA & Tokens & Cost (USD) \\",
        r"\midrule",
    ]
    for row in rows:
        ppa = f"{row.mean_ppa_passed:.3f}" if row.mean_ppa_passed is not None else "---"
        lines.append(
            f"{_tex(_provider(row))} & {_tex(row.model)} & {row.pass_count}/{row.tasks} & "
            f"{row.aggregate_score:.2f} & {ppa} & {row.tokens} & {row.cost_usd:.6f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / "paper" / "data" / "build" / "eval_table_16384.tex",
    )
    args = parser.parse_args(argv)

    try:
        rows = collect(args.root)
    except TableDataError as exc:
        parser.exit(2, f"table generation refused: {exc}\n")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(rows), encoding="utf-8", newline="\n")
    print(f"wrote {args.out} ({len(rows)} models)")
    for row in rows:
        print(f"  {row.model:30s} {row.pass_count:2d}/{row.tasks}  {row.aggregate_score:6.2f}  ${row.cost_usd:.4f}")
    print(f"  total cost: ${sum(row.cost_usd for row in rows):.4f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
