"""Generate the Track A run-to-run variance appendix from signed per-run manifests.

Reads three signed summary.json files per Anthropic model at the reported 16,384-token
condition: the already-committed single run (``results/eval-16384/<model>/summary.json``,
also Table 1's "single run" figure) as run 1, plus two fresh official re-runs
(``results/variance/run{2,3}/<model>/summary.json``) executed for exactly this purpose. This
closes the gap the paper previously disclosed in Appendix A: "the nine individual per-run
manifests this study is computed from are not currently committed to the repository alongside a
generator that reproduces the table's mean, standard deviation, and range from them." They now
are, and this script is that generator.
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from harness.schemas.canonical_json import compute_manifest_signature  # noqa: E402
from paper.data.generate_tables import TableDataError  # noqa: E402

RUN1_ROOT = REPO_ROOT / "results" / "eval-16384"
RUN2_ROOT = REPO_ROOT / "results" / "variance" / "run2"
RUN3_ROOT = REPO_ROOT / "results" / "variance" / "run3"
OUT_PATH = REPO_ROOT / "paper" / "data" / "build" / "variance_table.tex"
TASKS_ROOT = REPO_ROOT / "tasks"

MODELS = ("claude-opus-4-8", "claude-sonnet-4-6", "claude-haiku-4-5-20251001")


def _canonical_task_ids() -> frozenset[str]:
    return frozenset(path.parent.name for path in TASKS_ROOT.glob("*/task.yaml"))


def _load_summary(path: Path, *, model: str) -> dict:
    if not path.is_file():
        raise TableDataError(f"missing variance-study run: {path}")
    raw = json.loads(path.read_text(encoding="utf-8"))
    signature = raw.get("signature")
    if not isinstance(signature, str) or signature != compute_manifest_signature(raw):
        raise TableDataError(f"unsigned or tampered summary: {path}")
    if raw.get("provider") != "anthropic":
        raise TableDataError(f"{path}: provider must be anthropic, got {raw.get('provider')!r}")
    if raw.get("model") != model:
        raise TableDataError(f"{path}: model {raw.get('model')!r} != expected {model!r}")
    if raw.get("official") is not True:
        raise TableDataError(f"{path}: official must be true for the variance study")
    task_ids = raw.get("task_ids")
    if not isinstance(task_ids, list) or set(task_ids) != _canonical_task_ids():
        raise TableDataError(f"{path}: task_ids do not match the canonical 60-task suite")
    aggregate = raw.get("aggregate_mean")
    if not isinstance(aggregate, (int, float)):
        raise TableDataError(f"{path}: aggregate_mean missing or non-numeric")
    return raw


def collect(
    run1_root: Path = RUN1_ROOT, run2_root: Path = RUN2_ROOT, run3_root: Path = RUN3_ROOT
) -> dict[str, dict]:
    results: dict[str, dict] = {}
    seen_signatures: set[str] = set()
    for model in MODELS:
        runs = []
        for root in (run1_root, run2_root, run3_root):
            summary = _load_summary(root / model / "summary.json", model=model)
            if summary["signature"] in seen_signatures:
                raise TableDataError(
                    f"the same signed run appears twice in the variance study: "
                    f"{summary['signature']}"
                )
            seen_signatures.add(summary["signature"])
            runs.append(float(summary["aggregate_mean"]))
        mean = statistics.fmean(runs)
        std = statistics.stdev(runs)  # Bessel-corrected, n-1, matching the paper's caption
        results[model] = {
            "runs": runs,
            "mean": mean,
            "std": std,
            "range": max(runs) - min(runs),
            "single_run": runs[0],  # run 1 is the already-reported Table 1 figure
        }
    return results


def render(results: dict[str, dict]) -> str:
    lines = [
        "% generated by paper/data/generate_variance_appendix.py -- do not hand-edit",
        r"\begin{tabular}{lrrrr}",
        r"\toprule",
        r"Model & mean (n=3) & std & range & single run \\",
        r"\midrule",
    ]
    for model in MODELS:
        r = results[model]
        lines.append(
            f"{model} & {r['mean']:.2f} & {r['std']:.2f} & "
            f"{r['range']:.2f} & {r['single_run']:.2f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run1-root", type=Path, default=RUN1_ROOT)
    parser.add_argument("--run2-root", type=Path, default=RUN2_ROOT)
    parser.add_argument("--run3-root", type=Path, default=RUN3_ROOT)
    parser.add_argument("--out", type=Path, default=OUT_PATH)
    args = parser.parse_args(argv)

    try:
        results = collect(args.run1_root, args.run2_root, args.run3_root)
    except TableDataError as exc:
        parser.exit(2, f"variance appendix generation refused: {exc}\n")

    rendered = render(results)
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(rendered, encoding="utf-8", newline="\n")
    print(f"wrote {args.out}")
    for model in MODELS:
        r = results[model]
        print(
            f"  {model:30s} mean={r['mean']:.4f} std={r['std']:.4f} "
            f"range={r['range']:.4f} runs={[round(x, 4) for x in r['runs']]}"
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
