"""Generate the per-design RTLLM audit appendix table from raw committed audit JSON.

Deliberately separate from generate_tables.py: this reads only
external-audit/results/rtllm/final-g2012/*.json and emits one LaTeX fragment. Every number in the
appendix is derived here rather than hand-typed, so the table cannot drift from the raw evidence.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
AUDIT_DIR = REPO_ROOT / "external-audit" / "results" / "rtllm" / "final-g2012"
OUT_PATH = REPO_ROOT / "paper" / "data" / "build" / "audit_per_design.tex"


def _tex(value: str) -> str:
    return value.replace("_", r"\_")


def load_designs() -> tuple[list[dict], list[dict]]:
    audited: list[dict] = []
    unsupported: list[dict] = []
    for path in sorted(AUDIT_DIR.glob("*.json")):
        if path.name == "summary.json":
            continue
        data = json.loads(path.read_text(encoding="utf-8"))
        if data["status"] == "audited":
            audited.append(data)
        else:
            unsupported.append(data)
    return audited, unsupported


def alias_flag(notes: str) -> str:
    return "alias" if "module alias" in notes else "as shipped"


def render() -> str:
    audited, unsupported = load_designs()
    audited.sort(key=lambda d: (d["kill_rate"], d["task_id"]))

    lines: list[str] = []
    lines.append("% generated by paper/data/generate_audit_appendix.py -- do not hand-edit")
    lines.append(r"\begin{tabular}{lrrrrrl}")
    lines.append(r"\toprule")
    lines.append(
        r"Design & Mutants & Killed & Surv. & Indet. & Kill rate & Baseline \\"
    )
    lines.append(r"\midrule")
    for d in audited:
        lines.append(
            f"\\texttt{{{_tex(d['task_id'])}}} & {d['mutants_total']} & {d['killed']} & "
            f"{d['survived']} & {d['indeterminate']} & {d['kill_rate']:.1f}\\% & "
            f"{alias_flag(d.get('notes', ''))} \\\\"
        )
    total_m = sum(d["mutants_total"] for d in audited)
    total_k = sum(d["killed"] for d in audited)
    total_s = sum(d["survived"] for d in audited)
    total_i = sum(d["indeterminate"] for d in audited)
    lines.append(r"\midrule")
    lines.append(
        f"\\textbf{{Pooled ({len(audited)} audited)}} & \\textbf{{{total_m}}} & "
        f"\\textbf{{{total_k}}} & \\textbf{{{total_s}}} & \\textbf{{{total_i}}} & "
        f"\\textbf{{{100.0 * total_k / total_m:.1f}\\%}} & \\\\"
    )
    lines.append(r"\midrule")
    lines.append(r"\multicolumn{7}{l}{\emph{Reported \texttt{unsupported}: baseline"
                 r" validation failed, excluded from all aggregates}} \\")
    for d in unsupported:
        lines.append(
            f"\\texttt{{{_tex(d['task_id'])}}} & --- & --- & --- & --- & --- & "
            r"\texttt{unsupported} \\"
        )
    lines.append(r"\bottomrule")
    lines.append(r"\end{tabular}")
    return "\n".join(lines) + "\n"


def main() -> int:
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text(render(), encoding="utf-8", newline="\n")
    audited, unsupported = load_designs()
    print(f"audit_per_design.tex: audited={len(audited)} unsupported={len(unsupported)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
