"""Generate the Track A leaderboard for the raised-output-budget (16,384-token) campaign.

Kept separate from generate_tables.py, which owns the original 4096-token campaign tables. Reads a
results tree laid out as <root>/<model-dir>/summary.json and emits a LaTeX fragment.

Unlike the 4096 table this one reports Pass@1 and mean PPA over passed tasks as explicit columns:
the original table carried a constant "Tasks = 60" column that conveyed nothing, while Pass@1 --- the
metric that actually drives the ranking --- had to be recovered from the prose.
"""

from __future__ import annotations

import argparse
import json
import statistics
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]

PROVIDER_OF = {
    "claude-opus-4-8": "anthropic",
    "claude-sonnet-4-6": "anthropic",
    "claude-haiku-4-5-20251001": "anthropic",
    "gpt-5": "openai",
    "gpt-5-mini": "openai",
    "google/gemini-2.5-pro": "openrouter",
    "meta-llama/llama-4-maverick": "openrouter",
}


def _tex(value: str) -> str:
    return value.replace("_", r"\_").replace("&", r"\&")


def collect(root: Path) -> list[dict]:
    rows: list[dict] = []
    for summary in sorted(root.glob("*/summary.json")):
        data = json.loads(summary.read_text(encoding="utf-8"))
        model = data["model"]
        passed, ppas = 0, []
        for task in data["tasks"].values():
            score = task.get("mean_score")
            if score and score > 0:
                passed += 1
                ppas.append(score * 1.5 / 100.0)
        rows.append(
            {
                "provider": PROVIDER_OF.get(model, "?"),
                "model": model,
                "score": data["aggregate_mean"],
                "pass": passed,
                "mean_ppa": statistics.mean(ppas) if ppas else None,
                "tokens": data["tokens_in"] + data["tokens_out"],
                "cost": data["cost_usd"],
            }
        )
    rows.sort(key=lambda r: -r["score"])
    return rows


def render(rows: list[dict]) -> str:
    lines = [
        "% generated by paper/data/generate_tracka_16384.py -- do not hand-edit",
        r"\begin{tabular}{llrrrrr}",
        r"\toprule",
        r"Provider & Model & Pass@1 & Score & Mean PPA & Tokens & Cost (USD) \\",
        r"\midrule",
    ]
    for r in rows:
        ppa = f"{r['mean_ppa']:.3f}" if r["mean_ppa"] is not None else "---"
        lines.append(
            f"{_tex(r['provider'])} & {_tex(r['model'])} & {r['pass']}/60 & "
            f"{r['score']:.2f} & {ppa} & {r['tokens']} & {r['cost']:.6f} \\\\"
        )
    lines += [r"\bottomrule", r"\end{tabular}"]
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, required=True)
    parser.add_argument(
        "--out",
        type=Path,
        default=REPO_ROOT / "paper" / "data" / "build" / "eval_table_16384.tex",
    )
    args = parser.parse_args()

    rows = collect(args.root)
    if len(rows) != 7:
        print(f"WARNING: expected 7 models, found {len(rows)}: {[r['model'] for r in rows]}")
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(rows), encoding="utf-8", newline="\n")
    print(f"wrote {args.out} ({len(rows)} models)")
    for r in rows:
        print(f"  {r['model']:30s} {r['pass']:2d}/60  {r['score']:6.2f}  ${r['cost']:.4f}")
    print(f"  total cost: ${sum(r['cost'] for r in rows):.4f}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
